### ISSUE TITLE
Add download categories block

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-blocks#5]
It would be useful to have a block that allowed you to output the download categories with thumbnails, since this is used on pretty much every major eCommerce site homepage.

I have already built this for EDD as a shortcode (`download_categories`), using PHP, but not as aJavascript/Gutenberg block. 

Here is what it looks like:

<img width="1298" alt="screenshot 2018-07-27 15 55 58" src="https://user-images.githubusercontent.com/22668877/43328337-98badcbc-91b5-11e8-9937-9539f61ef8e4.png">

Within the admin panel, the ability to assign thumbnails on a per category basis was added to the download categories.

The shortcode accepts parameters such as `order_by`, `exclude_ids`, etc.

**Comment by amdrew** [comment]
I'd love to see this, it would be very useful for sites that sell stock photography, where they generally list categories of stock images on the homepage, rather than individual stock images.

We'd need EDD core to support setting an image on each download category. In the interim, we could use the featured image of the last download added to the category (or similar).

Related:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6659

**Comment by davidsherlock** [comment]
I wouldn't go with that option, since most featured images won't work well in that context. Maybe as a work around we allow the thumbnail to be set via the block at this time?

Either that or we push for this to be included in EDD core, I have already built it and would be happy to put include it in core if accepted. The code could be improved though, some it's a bit hacky to make it work as expected.

**Comment by amdrew** [comment]
Wouldn't be opposed at all to adding category image functionality to EDD Blocks. It would help to see how it functions as a proof of concept before a merge proposal.

**Comment by davidsherlock** [comment]
@amdrew, here is a gist with the class I built for adding images to download categories:

https://gist.github.com/davidsherlock/d9b9686081806cece8692e777aae30fb

This is for the most part a 'fork' of some code I found elsewhere, but it should provide an example of how it works.

Here is the code for the shortcode, please note that I created custom edd_template files for the actual rendering of the short-code elements.

https://gist.github.com/davidsherlock/67aa1ca5710720de33fd276b7d72ce76

**Comment by davidsherlock** [comment]
Nice! One suggestion - having the option/ability to use a `<ul>` styled list alternatively is something I added recently to my short-code as well, then using the CSS columns to allow you to split it into a standard list if you get me? Like this:

![screenshot 2018-08-08 13 27 35](https://user-images.githubusercontent.com/22668877/43836935-d3990838-9b0e-11e8-824d-8e714dd005cc.png)

Obviously having the ability to exclude specific taxonomy ids is important, regardless of layout styling used.

**Comment by amdrew** [comment]
## Some progress:

- The code @davidsherlock listed above for adding/removing images to the download category admin screen has been implemented. I tidied it up a bit but still needs some work. The "remove image" button shows when there isn't an image for example and there's some other jankiness with the (inline) CSS etc.

- Added an initial function for calling a list of download categories shown in a grid. We could further extend this to show in a `<ul>` as proposed above. We could also leave it as-is, since without an image or description it looks like separated lists in columns. If the markup is the concern then there could always be a filter to allow this to be changed.

- If a download category has an image added it's now shown in the block preview.

- A count can be toggled on/off. This is the number of downloads in each download category.

- Download categories can be ordered by `Count`, `ID`, `Name` or `Slug`.

- Download categories can be ordered `Ascending` or `Descending`

- There's a new toggle control for showing/hiding empty categories. Useful if there are no downloads added to a particular category.

## Things to do:

- [ ] Exclude specific terms. Still thinking about the best UI for this. Perhaps an "Exclude specific categories" or similar toggle control. Once toggled, a list of all terms will appear below in the block settings. You could then select individual terms and they will be removed from the block preview.

- [ ] Add a loader for when the component is fetching the download categories, in between state changes. This will ensure consistency with other core blocks.

- [ ] Perhaps a better UI for category images, directly within the block itself. This would allow someone to add/remove images for each download category, without having to go to each category admin page. If a category does not have an image we could show a grey placeholder box with an add/upload image button, similar to the core image block. A category's image could be swapped out by clicking on an edit icon in the top right hand corner of the image or similar.

- [ ] Improved CSS. Still needs some work to tackle some good responsive defaults. Aiming to keep CSS as lightweight as possible (with flexbox) and be shared with the downloads block. They're both grids so should use the same CSS wherever possible. This ideally would replace the CSS for the actual `downloads` shortcode in the future.

- [ ] Add shortcode. If we're going to have a download categories block, it would make sense to also have a `[download_categories]` shortcode as per https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6659. 

## One block to rule them all?

I've been considering just _1 block_ for outputting downloads, or download categories (and what about download tags?) but have purposely kept them separate for the time being. Something to consider.

We don't want too many blocks being added to the editor so if we're at all considering supporting download tags (I don't see why not) then perhaps we should refactor the downloads block to allow the user to choose between displaying `Downloads`, `Download Categories`, or `Download Tags`.

If we do this, it wouldn't make much sense creating separate shortcodes for [download_categories] and [download_tags], in addition to the [downloads] shortcode. One possible solution is to just extend the [downloads] shortcode to support this new type of output. Perhaps a type attribute or similar. E.g. `[downloads type="categories"]` or `[downloads type="tags"]`. When no attribute is specified it just defaults to downloads.

## Screenshots:

Front-end display:

<img width="1224" alt="screen shot 2018-08-12 at 2 33 35 pm" src="https://user-images.githubusercontent.com/52581/43997887-b7e80716-9e3c-11e8-9ba0-99f6c3219410.png">

___

Admin block preview (with count enabled):

<img width="1195" alt="screen shot 2018-08-12 at 2 20 18 pm" src="https://user-images.githubusercontent.com/52581/43997892-d00dd6b8-9e3c-11e8-9ba1-cf3618e61249.png">

___

Current block settings:

<img width="285" alt="screen shot 2018-08-12 at 2 20 33 pm" src="https://user-images.githubusercontent.com/52581/43997894-dcf9f9e2-9e3c-11e8-9598-0dddebc566c4.png">

**Comment by amdrew** [comment]
Merged PR into master for further testing.

**Comment by amdrew** [comment]
This has now been merged into the downloads block and can be enabled via the `Display` option in the block settings. Has all the same settings as before.

<img width="284" alt="screen shot 2018-10-29 at 2 15 27 pm" src="https://user-images.githubusercontent.com/52581/47624815-1d174e00-db85-11e8-9bfd-38a2adbb67a9.png">

**Comment by amdrew** [comment]
Closing, any outstanding tasks have been separated into new issues.
